name: SFU Anime Cog Tests
on:
  pull_request:
  push:
  repository_dispatch:
    types:
      - dispatched_test

env:
  ref: ${{ github.event.client_payload.ref || '' }}

jobs:
    tox:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python_version:
            - "3.8"
        fail-fast: false
      name: Tests - SFU Anime Cogs
      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ env.ref }}
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python_version }}
        - name: Install bot
          run: |
            python setup.py install
        - name: Install pytest
          run: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install pytest-asyncio
        - name: Set up Red
          run: |
            printf "Test\ny\ny\n1\n" | redbot-setup
        - name: Run tests
          run: |
            pytest cogs/*/test*.py
